# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    name: check
    runs-on: ubuntu-24.04-arm
    container: fedora@sha256:6c75d5bf57cb0fa5aa4b92c6a83c86c791644496d9ac230de7711f5b8ec3b898
    steps:
    - uses: actions/checkout@v5
    - name: Install rpmlint
      run: dnf install -y git rpmlint rpmdevtools
    - name: rpmlint
      run: rpmlint specs/ --strict
    - name: Install build dependencies
      run: dnf install -y cargo pandoc rust
    - name: Build RPM
      run: |
        for file in `ls specs/`; do
          echo "Building specs/$file..."
          spectool -Rg "specs/$file"
          rpmbuild -ba "specs/$file"
        done
